# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacktower" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "3ab5b3932baa317a49ec008c9c0998ec74bb86571344beee82b06c24cc505947"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d38631ca1bcd80b0bb8965a2fc3acda44d4a0234676ee53b9c8476381c033dbb"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3593cceb49bedf1a9fa30ce81a86dc96d905fb8c0e23bd6923d2164e58fead3"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "834fca2f049daf63da03ced7ca35b5c420bbd25fda13c24a6ef17b3f0a1ab7bf"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stacktower"
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/stacktower-io/stacktower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacktower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacktower"]
    end
  end

  # No zap stanza required

end
