# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacktower" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "62cd0aed7d4f2338c5126c32fb9c12bd1a00ff4cde5806eac84932a84a6c673a"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1e3188377298683b4d9405cc2172dce2ea70ef9dce9ac2219a98e28610d77a4e"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be6e47febefae4e07b73d726aef5151144b834546d075e59da8bd56e6a603cb3"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "53f9ea65926b3c11306e2846220eb32e553a0fb923f34332714a0d8044d2191e"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stacktower"
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/stacktower-io/stacktower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacktower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacktower"]
    end
  end

  # No zap stanza required

end
