# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "1.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.4/stacktower_1.1.4_Darwin_x86_64.tar.gz"
      sha256 "d732d45aae072ab55ca1b3471d6cb939d806bb1070aa631a16b14daf0dfcff0b"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.4/stacktower_1.1.4_Darwin_arm64.tar.gz"
      sha256 "28956bfe12562dfdf2d46feb3dac35daf77bf3ef0502798931626bef6835a41e"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.4/stacktower_1.1.4_Linux_x86_64.tar.gz"
      sha256 "623df5358e62726f1ec7c380caf3b954a65d8fa7cc9a6a9f70bf413c838278fe"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.4/stacktower_1.1.4_Linux_arm64.tar.gz"
      sha256 "1efe021c73a264b9f4db99beb30fbe75655ac47289cd735117f4d8e62b8ebbee"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
