# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.0/stacktower_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "b19a9a12c8ea851073b8a105d8f033320a53ec52b69336ed3aa39fe073efad26"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.0/stacktower_1.1.0_Darwin_arm64.tar.gz"
      sha256 "e6777ff070e3645accdc8879ed3ba3e1958519c99e4aacb6733579487bcfa791"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.0/stacktower_1.1.0_Linux_x86_64.tar.gz"
      sha256 "94b9c4274c539619008cf06f656434bb3be4fce256d6f53c2c821e4456e4c2af"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.1.0/stacktower_1.1.0_Linux_arm64.tar.gz"
      sha256 "4fb206f32b17c01e4311c40797316480c9d498c667656dbd1af8769d9728db1c"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
