# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.2.0/stacktower_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "a662f390cf65bf03ef3e68aeb7919568908281329d9bfd18504303f7b519b28e"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.2.0/stacktower_1.2.0_Darwin_arm64.tar.gz"
      sha256 "618e83be4e7e2eb3f8aa9cb645c5a1ad4730057d1ab12f432f6378077b978157"

      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.2.0/stacktower_1.2.0_Linux_x86_64.tar.gz"
      sha256 "d6df4965630945a7e8a99c175f4f627f38137e0c1c8400dc7c9d498b0830d3b5"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v1.2.0/stacktower_1.2.0_Linux_arm64.tar.gz"
      sha256 "e7bbd6729cbf082aa8c5aa98cb8071ea6ee3cfb9421710f0751e5dc9674eb8f2"
      define_method(:install) do
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
